#!/bin/bash
# Script de instrucciones para GitHub y Netlify

echo "╔════════════════════════════════════════════════════════════╗"
echo "║     🚀 PUBLICAR KAPI TASK BOARD EN GITHUB Y NETLIFY      ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

echo "📋 PASO 1: Crear repositorio en GitHub"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Ve a: https://github.com/new"
echo "2. Rellena:"
echo "   - Repository name: KAPI-Task"
echo "   - Description: Kanban Task Board - React + Vite + Tailwind CSS"
echo "   - Public"
echo "3. NO marques 'Initialize this repository with...'"
echo "4. Haz clic en 'Create repository'"
echo ""

echo "📝 PASO 2: Conectar con GitHub"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Ejecuta estos comandos (reemplaza YOUR_USERNAME):"
echo ""
echo "git remote add origin https://github.com/YOUR_USERNAME/KAPI-Task.git"
echo "git branch -M main"
echo "git push -u origin main"
echo ""

echo "🌐 PASO 3: Desplegar en Netlify"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Ve a: https://netlify.com"
echo "2. Inicia sesión o crea cuenta"
echo "3. Haz clic en 'Add new site' → 'Import an existing project'"
echo "4. Selecciona GitHub como proveedor"
echo "5. Busca y selecciona KAPI-Task"
echo "6. Haz clic en 'Deploy site'"
echo "7. ¡Espera 2-5 minutos!"
echo ""

echo "✅ VERIFICAR"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Netlify te dará una URL como: https://xxxxx.netlify.app"
echo ""
echo "Verifica que:"
echo "  ✓ La app carga correctamente"
echo "  ✓ Puedes crear y editar tareas"
echo "  ✓ El drag & drop funciona"
echo "  ✓ El modo oscuro funciona"
echo ""

echo "🔄 FLUJO FUTURO"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Después de esto, solo necesitas:"
echo ""
echo "git add ."
echo "git commit -m 'Tu mensaje'"
echo "git push"
echo ""
echo "¡Netlify redeploy automáticamente!"
echo ""

echo "📚 DOCUMENTACIÓN"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Lee el archivo: GITHUB_NETLIFY.md para instrucciones detalladas"
echo ""

echo "╚════════════════════════════════════════════════════════════╝"
